# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file '_logical_async.py'
# DO NOT CHANGE! Change the original file instead.
# Copyright (C) 2025 The Psycopg Team

from __future__ import annotations

from types import TracebackType
from typing import TYPE_CHECKING, Iterator, Literal, Sequence

from . import adapt
from . import errors as e
from . import generators, pq, waiting
from .abc import Transformer
from .rows import DictRow
from .pq.abc import PGconn
from ._compat import Self
from ._pgoutput import ChangeEvent, PgOutputDecoder
from ._logical_base import (
    CreateSlotResult,
    IdentifySystemResult,
    _escape_option_value,
    _pg_now_us,
)

if TYPE_CHECKING:
    from .cursor import Cursor

# Helpers


class LogicalStream:
    """Logical replication stream over a dedicated PGconn in CopyBoth mode."""

    __slots__ = (
        "_pgconn",
        "_decoder",
        "_write_lsn",
        "_flush_lsn",
        "_apply_lsn",
        "_last_received_lsn",
        "_last_flushed_lsn",
        "_last_applied_lsn",
    )

    def __init__(self, pgconn: PGconn, *, transformer: Transformer) -> None:
        self._pgconn = pgconn
        self._decoder = PgOutputDecoder(transformer)

        self._write_lsn = 0
        self._flush_lsn = 0
        self._apply_lsn = 0

        self._last_received_lsn = 0
        self._last_flushed_lsn = 0
        self._last_applied_lsn = 0

    def __enter__(self) -> Self:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        self.close()

    def __iter__(self) -> Iterator[ChangeEvent]:
        return self._run()

    def ack(
        self,
        lsn: int,
        *,
        write: bool = True,
        flush: bool = True,
        apply: bool = True,
        request_reply: bool = False,
    ) -> None:
        """Send a Standby Status Update (acknowledgement) to the server.

        - lsn: the WAL LSN to acknowledge.
        - write/flush/apply: which of the three LSNs to set to this value.
        - request_reply: request an immediate keepalive reply from the server.
        """
        if write:
            self._write_lsn = max(self._write_lsn, lsn)
        if flush:
            self._flush_lsn = max(self._flush_lsn, lsn)
            self._last_flushed_lsn = self._flush_lsn
        if apply:
            self._apply_lsn = max(self._apply_lsn, lsn)
            self._last_applied_lsn = self._apply_lsn
        self._send_status_update(request_reply=request_reply)

    @property
    def last_received_lsn(self) -> int:
        return self._last_received_lsn

    @property
    def last_flushed_lsn(self) -> int:
        return self._last_flushed_lsn

    @property
    def last_applied_lsn(self) -> int:
        return self._last_applied_lsn

    def close(self) -> None:
        # End the replication copy-both mode
        waiting.wait(generators.copy_both_end(self._pgconn, None), self._pgconn.socket)
        # Get the result of the START_REPLICATION
        waiting.wait(generators.fetch_many(self._pgconn), self._pgconn.socket)
        self._decoder.clear_caches()

    def _run(self) -> Iterator[ChangeEvent]:
        while True:
            res = waiting.wait(generators.copy_from(self._pgconn), self._pgconn.socket)

            if isinstance(res, memoryview):
                tag = chr(res[0])
                payload = res[1:]
                # XLogData

                # Primary keepalive message
                match tag:
                    case "w":
                        if len(payload) < 24:
                            raise e.InterfaceError("short XLogData")
                        start_lsn = int.from_bytes(payload[0:8])
                        # end_lsn = int.from_bytes(payload[8:16])
                        # server_time = int.from_bytes(payload[16:24])
                        xlogdata = payload[24:]

                        self._last_received_lsn = start_lsn

                        for ev in self._decoder.parse_xlogdata(xlogdata, lsn=start_lsn):
                            yield ev
                    case "k":
                        if len(payload) < 17:
                            raise e.InterfaceError("short primary keepalive message")
                        # server_end_lsn = int.from_bytes(payload[0:8])
                        # server_time = int.from_bytes(payload[8:16])
                        reply_requested = payload[16] != 0
                        if reply_requested:
                            self._send_status_update(request_reply=True)
                    case _:
                        raise e.InterfaceError(f"unknown replication frame: {tag!r}")
            else:
                break

    def _send_status_update(self, *, request_reply: bool) -> None:
        payload = bytearray(1 + 8 + 8 + 8 + 8 + 1)
        payload[0] = ord("r")  # Standby status update
        payload[1:9] = self._write_lsn.to_bytes(8)
        payload[9:17] = self._flush_lsn.to_bytes(8)
        payload[17:25] = self._apply_lsn.to_bytes(8)
        payload[25:33] = _pg_now_us().to_bytes(8)
        payload[33] = 1 if request_reply else 0

        waiting.wait(generators.copy_to(self._pgconn, payload), self._pgconn.socket)


class Logical:
    """Manage a logical decoding connection.

    :param cursor: a client cursor for a logical replication connection.
    """

    __slots__ = ("_cursor", "_pgconn", "_adapters")

    def __init__(self, cursor: Cursor[DictRow]) -> None:
        self._cursor = cursor
        self._pgconn = cursor.connection.pgconn
        self._adapters = cursor.adapters

        self._pgconn.trace(1)

    def close(self) -> None:
        self._cursor.close()

    def __enter__(self) -> Self:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        self.close()

    def identify_system(self) -> IdentifySystemResult:
        """Requests the server to identify itself."""
        self._cursor.execute("IDENTIFY_SYSTEM")
        result = self._cursor.fetchone()

        if result is None:
            raise e.InterfaceError("no result from IDENTIFY_SYSTEM")
        try:
            systemid = result["systemid"]
            timeline = result["timeline"]
            xlogpos = result["xlogpos"]
            dbname = result["dbname"]
        except KeyError as exc:
            raise e.InterfaceError(
                f"IDENTIFY_SYSTEM response missing field: {exc}"
            ) from None
        if (
            not isinstance(systemid, str)
            or not isinstance(timeline, int)
            or (not isinstance(xlogpos, str))
            or (not (dbname is None or isinstance(dbname, str)))
        ):
            raise e.InterfaceError("IDENTIFY_SYSTEM response field has unexpected type")

        return IdentifySystemResult(
            systemid=systemid, timeline=timeline, xlogpos=xlogpos, dbname=dbname
        )

    def create_logical_slot(
        self,
        name: str,
        *,
        temporary: bool = False,
        two_phase: bool = False,
        snapshot: Literal["export", "use", "nothing"] = "export",
        failover: bool | None = None,
    ) -> CreateSlotResult:
        """Create a logical replication slot using the pgoutput logical decoding
        output plugin.

        :param temporary:
            Create a temporary slot. A temporary slot is dropped automatically
            on disconnect.
        :param two_phase:
            Enable decoding of two-phase transactions (server >= 15).
        :param snapshot:
            'export' -> EXPORT_SNAPSHOT
            'use' -> USE_SNAPSHOT
            'nothing' -> NOEXPORT_SNAPSHOT (or omitted)
        :param failover:
            If True add FAILOVER, if False add NOFAILOVER, if None omit (server >= 16).
        """
        temp_sql = " TEMPORARY" if temporary else ""
        cmd = f"CREATE_REPLICATION_SLOT {name}{temp_sql} LOGICAL pgoutput"
        if snapshot == "export":
            snap_sql = " EXPORT_SNAPSHOT"
        elif snapshot == "use":
            snap_sql = " USE_SNAPSHOT"
        elif snapshot == "nothing":
            snap_sql = " NOEXPORT_SNAPSHOT"
        else:
            raise e.ProgrammingError(f"invalid snapshot value: {snapshot!r}")
        flags: list[str] = []
        if two_phase:
            flags.append(" TWO_PHASE")
        if failover is True:
            flags.append(" FAILOVER")
        elif failover is False:
            flags.append(" NOFAILOVER")
        sql = cmd + snap_sql + "".join(flags)

        self._cursor.execute(sql)
        result = self._cursor.fetchone()

        if not result:
            raise e.InterfaceError("no results from CREATE_REPLICATION_SLOT")
        try:
            slot_name = result["slot_name"]
            consistent_point = result["consistent_point"]
            snapshot_name = result["snapshot_name"]
            output_plugin = result["output_plugin"]
        except KeyError as exc:
            raise e.InterfaceError(
                f"CREATE_REPLICATION_SLOT response missing field: {exc}"
            ) from None
        if (
            not isinstance(slot_name, str)
            or not isinstance(consistent_point, str)
            or (not (snapshot_name is None or isinstance(snapshot_name, str)))
            or (not isinstance(output_plugin, str))
        ):
            raise e.InterfaceError(
                "CREATE_REPLICATION_SLOT response field has unexpected type"
            )

        return CreateSlotResult(
            slot_name=slot_name,
            consistent_point=consistent_point,
            snapshot_name=snapshot_name,
            output_plugin=output_plugin,
        )

    def drop_replication_slot(self, name: str, *, wait: bool = False) -> None:
        """Drop a replication slot.

        When wait=True, use WAIT to ensure resources are freed.
        """
        sql = f"DROP_REPLICATION_SLOT {name}{(' WAIT' if wait else '')}"

        self._cursor.execute(sql)
        self._cursor.fetchall()

    def stream(
        self,
        slot: str,
        *,
        publications: Sequence[str],
        start_lsn: str | None,
        messages: bool = False,
        binary: bool = False,
    ) -> LogicalStream:
        """Instruct the server to start streaming logical replication messages
        and return the stream.

        :param slot:
            Replication slot name.
        :param publications:
            Publication names (at least one).
        :param start_lsn:
            LSN to start from (None to let server decide).
        :param messages:
            Whether to include generic logical decoding messages, such as
            emitted by `pg_logical_emit_message()`.
        """
        lsn = start_lsn or "0/0"
        options = {
            "proto_version": "1",
            "publication_names": ",".join(publications),
            "binary": "true" if binary else "false",
            "messages": "true" if messages else "false",
        }
        opt_list = []
        if options:
            for k, v in options.items():
                opt_list.append(f"{k} '{_escape_option_value(v)}'")
        opt_sql = f" ({', '.join(opt_list)})" if opt_list else ""
        sql = f"START_REPLICATION SLOT {slot} LOGICAL {lsn}{opt_sql};"

        # Send query and enter CopyBoth.
        self._pgconn.send_query(sql.encode())
        waiting.wait(generators.send(self._pgconn), self._pgconn.socket)
        results = waiting.wait(generators.fetch_many(self._pgconn), self._pgconn.socket)
        if not results or results[0].status != pq.ExecStatus.COPY_BOTH:
            status = results[0].status if results else None
            raise e.ProgrammingError(
                f"failed to start logical replication (status: {status})"
            )

        transformer = adapt.Transformer(self._adapters)
        return LogicalStream(self._pgconn, transformer=transformer)
