# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file '_replication_conn_async.py'
# DO NOT CHANGE! Change the original file instead.
# Copyright (C) 2025 The Psycopg Team

from __future__ import annotations

import time
from types import TracebackType
from typing import Iterator, Literal, Sequence

from . import adapt
from . import errors as e
from . import generators, pq, waiting
from .abc import PQGen, Transformer
from .pq.abc import PGconn, PGresult
from ._compat import Self
from .conninfo import make_conninfo
from ._pgoutput import ChangeEvent, PgOutputDecoder
from ._replication_conn_base import (
    CreateSlotResult,
    IdentifySystem,
    _decode_row_as_dict,
    _escape_option_value,
    _pg_now_us,
)

_WAIT_INTERVAL = 0.1

# Helpers


def _exec_simple(pgconn: pq.abc.PGconn, sql: str) -> list[pq.abc.PGresult]:
    """Execute a simple query on a non-blocking PGconn and return all results."""
    pgconn.send_query(sql.encode())
    waiting.wait(generators.send(pgconn), pgconn.socket, interval=_WAIT_INTERVAL)
    results = waiting.wait(
        generators.fetch_many(pgconn), pgconn.socket, interval=_WAIT_INTERVAL
    )
    return results


class LogicalStream:
    """Logical replication stream over a dedicated PGconn in CopyBoth mode.

    Implements:
    - Context manager to ensure CopyDone and result draining on close.
    - Iterable yielding ChangeEvent(s) decoded via PgOutputDecoder.
    - ack() to send Standby Status Update mapping write/flush/apply LSNs.
    - set_status_interval() to control periodic status updates.
    - Properties for last_received_lsn/last_flushed_lsn/last_applied_lsn.
    """

    __slots__ = (
        "_pgconn",
        "_decoder",
        "_status_interval",
        "_last_status_sent",
        "_closed",
        "_write_lsn",
        "_flush_lsn",
        "_apply_lsn",
        "_last_received_lsn",
        "_last_flushed_lsn",
        "_last_applied_lsn",
    )

    def __init__(self, pgconn: PGconn, *, transformer: Transformer) -> None:
        self._pgconn = pgconn
        self._decoder = PgOutputDecoder(transformer)
        self._status_interval = 10.0
        self._last_status_sent = 0.0
        self._closed = False

        self._write_lsn = 0
        self._flush_lsn = 0
        self._apply_lsn = 0

        self._last_received_lsn = 0
        self._last_flushed_lsn = 0
        self._last_applied_lsn = 0

    # Public API

    def __enter__(self) -> Self:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        self.close()

    def __iter__(self) -> Iterator[ChangeEvent]:
        return self._run()

    def ack(
        self,
        lsn: int,
        *,
        write: bool = True,
        flush: bool = True,
        apply: bool = True,
        request_reply: bool = False,
    ) -> None:
        """Send a Standby Status Update (acknowledgement) to the server.

        - lsn: the WAL LSN to acknowledge.
        - write/flush/apply: which of the three LSNs to set to this value.
        - request_reply: request an immediate keepalive reply from the server.
        """
        if write:
            self._write_lsn = max(self._write_lsn, lsn)
        if flush:
            self._flush_lsn = max(self._flush_lsn, lsn)
            self._last_flushed_lsn = self._flush_lsn
        if apply:
            self._apply_lsn = max(self._apply_lsn, lsn)
            self._last_applied_lsn = self._apply_lsn
        self._send_status_update(request_reply=request_reply)

    def set_status_interval(self, seconds: float) -> None:
        self._status_interval = float(seconds)

    @property
    def last_received_lsn(self) -> int:
        return self._last_received_lsn

    @property
    def last_flushed_lsn(self) -> int:
        return self._last_flushed_lsn

    @property
    def last_applied_lsn(self) -> int:
        return self._last_applied_lsn

    def close(self) -> None:
        """End CopyBoth by sending CopyDone and draining the server's response.

        Safe to call multiple times.
        """
        if self._closed:
            return
        self._closed = True

        try:
            _ = waiting.wait(self._copy_end_gen(error=None), self._pgconn.socket)
        except Exception:
            return

        self._decoder.clear_caches()

    # Internal: main loop (async)

    def _run(self) -> Iterator[ChangeEvent]:
        while True:
            nbytes, data = waiting.wait(self._recv_copy_data_gen(), self._pgconn.socket)

            if nbytes > 0:
                buf = data
                tag = chr(buf[0])
                payload = buf[1:]

                self._maybe_send_periodic_status()
                # XLogData

                # Primary keepalive message
                match tag:
                    case "w":
                        if len(payload) < 24:
                            raise e.InterfaceError("short XLogData")
                        start_lsn = int.from_bytes(payload[0:8])
                        # end_lsn = int.from_bytes(payload[8:16])
                        # server_time = int.from_bytes(payload[16:24])
                        xlogdata = payload[24:]

                        self._last_received_lsn = start_lsn

                        for ev in self._decoder.parse_xlogdata(xlogdata, lsn=start_lsn):
                            yield ev
                    case "k":
                        if len(payload) < 17:
                            raise e.InterfaceError("short primary keepalive message")
                        # server_end_lsn = int.from_bytes(payload[0:8])
                        # server_time = int.from_bytes(payload[8:16])
                        reply_requested = payload[16] != 0
                        if reply_requested:
                            self._send_status_update(request_reply=True)
                    case _:
                        raise e.InterfaceError(f"unknown replication frame: {tag!r}")

                continue

            if nbytes == -1:
                _ = waiting.wait(self._fetch_final_result_gen(), self._pgconn.socket)
                break

            if nbytes == -2:
                raise e.OperationalError("error while reading replication stream")

        return

    # Internal: IO helpers

    def _recv_copy_data_gen(self) -> PQGen[tuple[int, memoryview[int]]]:
        while True:
            nbytes, data = self._pgconn.get_copy_data(1)
            if nbytes != 0:
                break
            while not (yield waiting.WAIT_R):
                continue
            self._pgconn.consume_input()
        return (nbytes, data)

    def _send_copy_data_gen(self, buffer: bytes) -> PQGen[None]:
        while self._pgconn.put_copy_data(buffer) == 0:
            while not (yield waiting.WAIT_W):
                continue
        while True:
            while not (yield waiting.WAIT_W):
                continue
            if self._pgconn.flush() == 0:
                break
        return None

    def _copy_end_gen(self, error: bytes | None) -> PQGen[PGresult]:
        while self._pgconn.put_copy_end(error) == 0:
            while not (yield waiting.WAIT_W):
                continue
        while True:
            while not (yield waiting.WAIT_W):
                continue
            if self._pgconn.flush() == 0:
                break
        (result,) = yield from generators.fetch_many(self._pgconn)
        if result.status != pq.ExecStatus.COMMAND_OK:
            raise e.error_from_result(result, encoding=self._pgconn._encoding)
        return result

    def _fetch_final_result_gen(self) -> PQGen[list[PGresult]]:
        results = yield from generators.fetch_many(self._pgconn)
        if results and results[0].status != pq.ExecStatus.COMMAND_OK:
            raise e.error_from_result(results[0], encoding=self._pgconn._encoding)
        return results

    # Internal: status updates

    def _maybe_send_periodic_status(self) -> None:
        now = time.monotonic()
        if self._status_interval > 0.0:
            if (
                self._last_status_sent == 0.0
                or now - self._last_status_sent >= self._status_interval
            ):
                self._send_status_update(request_reply=False)

    def _send_status_update(self, *, request_reply: bool) -> None:
        payload = bytearray(1 + 8 + 8 + 8 + 8 + 1)
        payload[0] = ord("r")  # Standby status update
        payload[1:9] = self._write_lsn.to_bytes(8)
        payload[9:17] = self._flush_lsn.to_bytes(8)
        payload[17:25] = self._apply_lsn.to_bytes(8)
        payload[25:33] = _pg_now_us().to_bytes(8)
        payload[33] = 1 if request_reply else 0

        waiting.wait(self._send_copy_data_gen(bytes(payload)), self._pgconn.socket)
        self._last_status_sent = time.monotonic()


class ReplicationConnection:
    """Replication connection (replication=database).

    Use connect() to create a connection dedicated to logical replication and
    use the provided methods to manage slots.
    """

    __slots__ = ("_pgconn", "_adapters")

    def __init__(self, pgconn: pq.abc.PGconn, adapters: adapt.AdaptersMap) -> None:
        self._pgconn = pgconn
        self._adapters = adapt.AdaptersMap(adapters)

    @classmethod
    def connect(cls, dsn: str, adapters: adapt.AdaptersMap) -> Self:
        """Open an async replication connection forcing replication=database."""
        rconninfo = make_conninfo(dsn, replication="database")
        pgconn = waiting.wait_conn(
            generators.connect(rconninfo), interval=_WAIT_INTERVAL
        )
        return cls(pgconn, adapters)

    def close(self) -> None:
        self._pgconn.finish()

    def __enter__(self) -> Self:
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    def identify_system(self) -> IdentifySystem:
        """Run IDENTIFY_SYSTEM and return parsed information."""
        results = _exec_simple(self._pgconn, "IDENTIFY_SYSTEM;")
        if not results:
            raise e.InterfaceError("no results from IDENTIFY_SYSTEM")

        res = results[0]
        if res.status != pq.ExecStatus.TUPLES_OK:
            raise e.error_from_result(res, encoding=self._pgconn._encoding)

        row = _decode_row_as_dict(res)

        # Expected keys: systemid, timeline, xlogpos, dbname (optional)
        systemid = row["systemid"]
        timeline_s = row["timeline"]
        xlogpos = row["xlogpos"]
        dbname = row["dbname"]

        if systemid is None or timeline_s is None or xlogpos is None:
            raise e.InterfaceError("IDENTIFY_SYSTEM response missing required fields")
        try:
            timeline = int(timeline_s)
        except ValueError:
            raise e.InterfaceError(f"bad timeline value: {timeline_s!r}")

        return IdentifySystem(
            systemid=systemid, timeline=timeline, xlogpos=xlogpos, dbname=dbname
        )

    def create_logical_slot(
        self,
        name: str,
        plugin: str = "pgoutput",
        *,
        temporary: bool = False,
        two_phase: bool = False,
        snapshot: Literal["export", "use", "nothing"] = "export",
        failover: bool | None = None,
    ) -> CreateSlotResult:
        """Create a logical replication slot.

        - temporary: create a temporary slot (dropped automatically on disconnect)
        - two_phase: enable decoding of two-phase transactions (server >= 15)
        - snapshot: 'export' -> EXPORT_SNAPSHOT, 'use' -> USE_SNAPSHOT,
                    'nothing' -> NOEXPORT_SNAPSHOT (or omitted)
        - failover: if True add FAILOVER, if False add NOFAILOVER, if None omit
                    (server >= 16)
        """
        # Base command
        temp_sql = " TEMPORARY" if temporary else ""
        cmd = f"CREATE_REPLICATION_SLOT {name}{temp_sql} LOGICAL {plugin}"

        # Snapshot behavior
        if snapshot == "export":
            snap_sql = " EXPORT_SNAPSHOT"
        elif snapshot == "use":
            snap_sql = " USE_SNAPSHOT"
        elif snapshot == "nothing":
            # Historically NOEXPORT_SNAPSHOT; supported from PG12.
            snap_sql = " NOEXPORT_SNAPSHOT"
        else:
            raise e.ProgrammingError(f"invalid snapshot value: {snapshot!r}")

        # Optional flags (best-effort; server may ignore unknowns)
        flags: list[str] = []
        if two_phase:
            flags.append(" TWO_PHASE")
        if failover is True:
            flags.append(" FAILOVER")
        elif failover is False:
            flags.append(" NOFAILOVER")

        sql = cmd + snap_sql + "".join(flags) + ";"

        results = _exec_simple(self._pgconn, sql)
        if not results:
            raise e.ProgrammingError("no results from CREATE_REPLICATION_SLOT")

        res = results[0]
        if res.status != pq.ExecStatus.TUPLES_OK:
            raise e.error_from_result(res, encoding=self._pgconn._encoding)

        row = _decode_row_as_dict(res)

        # Columns: slot_name, consistent_point, snapshot_name, output_plugin
        slot_name = row.get("slot_name") or name
        consistent_point = row.get("consistent_point") or "0/00000000"
        snapshot_name = row.get("snapshot_name")
        output_plugin = row.get("output_plugin") or plugin

        return CreateSlotResult(
            slot_name=slot_name,
            consistent_point=consistent_point,
            snapshot_name=snapshot_name,
            output_plugin=output_plugin,
        )

    def drop_replication_slot(self, name: str, *, wait: bool = False) -> None:
        """Drop a replication slot.

        When wait=True, use WAIT to ensure resources are freed.
        """
        sql = f"DROP_REPLICATION_SLOT {name}{(' WAIT' if wait else '')};"
        results = _exec_simple(self._pgconn, sql)
        if not results:
            raise e.ProgrammingError("no results from DROP_REPLICATION_SLOT")

        res = results[0]
        if res.status != pq.ExecStatus.COMMAND_OK:
            raise e.error_from_result(res, encoding=self._pgconn._encoding)

    def start_logical(
        self,
        slot: str,
        *,
        publications: Sequence[str],
        start_lsn: str | None,
        messages: bool,
    ) -> LogicalStream:
        """Instruct the server to start streaming logical replication messages
        and return the stream.

        :param slot: replication slot name.
        :param publications: publication names (at least one).
        :param start_lsn: LSN to start from (e.g., '0/0' to let server decide).
        :param messages: whether to include generic logical decoding messages,
                         such as emitted by `pg_logical_emit_message()`.
        """
        lsn = start_lsn or "0/0"
        options = {
            "proto_version": "1",
            "binary": "false",
            "publication_names": ",".join(publications),
            "messages": "true" if messages else "false",
        }
        opt_list = []
        if options:
            for k, v in options.items():
                opt_list.append(f"{k} '{_escape_option_value(v)}'")
        opt_sql = f" ({', '.join(opt_list)})" if opt_list else ""
        cmd = f"START_REPLICATION SLOT {slot} LOGICAL {lsn}{opt_sql};"

        # Send query and enter CopyBoth
        self._pgconn.send_query(cmd.encode())
        waiting.wait(generators.send(self._pgconn), self._pgconn.socket)
        results = waiting.wait(generators.fetch_many(self._pgconn), self._pgconn.socket)
        if not results or results[0].status != pq.ExecStatus.COPY_BOTH:
            status = results[0].status if results else None
            raise e.ProgrammingError(
                f"failed to start logical replication (status: {status})"
            )

        transformer = adapt.Transformer(self._adapters)
        return LogicalStream(self._pgconn, transformer=transformer)
