# WARNING: this file is auto-generated by 'async_to_sync.py'
# from the original file 'test_logical_async.py'
# DO NOT CHANGE! Change the original file instead.
import threading
from unittest import mock

import pytest

import psycopg

from .acompat import sleep


@pytest.mark.anyio
def test_subscribe_end_to_end(dsn: str) -> None:
    table = "lr_tab"
    publication = "lr_pub"

    def producer() -> None:
        # Small delay to allow the subscriber to enter COPY_BOTH.
        sleep(0.5)
        with psycopg.Connection.connect(
            dsn
        ) as conn, conn.transaction(), conn.cursor() as cursor:
            cursor.execute(
                f"insert into {table} (name, qty) values (%s, %s) returning id",
                ("one", 1),
            )
            row_id = next(cursor)[0]

            cursor.execute(
                f"update {table} set name = %s, qty = %s where id = %s",
                ("two", 2, row_id),
            )

            cursor.execute(
                "select pg_logical_emit_message(true, 'some-prefix', 'updated!')"
            )

            cursor.execute(f"delete from {table} where id = %s", (row_id,))

    events: list[psycopg.ChangeEvent] = []

    def consumer() -> None:
        with psycopg.Connection.connect(
            dsn, autocommit=True, replication="database"
        ) as conn:
            with conn.logical() as logical:
                slot = logical.create_logical_slot("test_slot", temporary=True)
                with logical.stream(
                    slot.slot_name,
                    publications=[publication],
                    start_lsn="0/0",
                    messages=True,
                ) as stream:
                    for ev in stream:
                        events.append(ev)
                        stream.ack(ev.lsn)
                        if isinstance(ev, psycopg.Commit):
                            break

    with psycopg.connect(dsn) as base:
        try:
            with base.transaction(), base.cursor() as cursor:
                cursor.execute("show wal_level")
                wal_level = next(cursor)[0]
                if str(wal_level) != "logical":
                    pytest.skip(f"wal_level is {wal_level!r} (need 'logical')")

                cursor.execute(f"drop table if exists {table} cascade")
                cursor.execute(
                    f"create table {table} (id serial primary key, name text, qty int)"
                )
                cursor.execute(f"drop publication if exists {publication}")
                cursor.execute(f"create publication {publication} for table {table}")

            producer_task = threading.Thread(target=producer)
            consumer_task = threading.Thread(target=consumer)
            producer_task.start()
            consumer_task.start()
            producer_task.join()
            consumer_task.join()
        finally:
            with base.transaction(), base.cursor() as cursor:
                cursor.execute(f"drop publication if exists {publication}")
                cursor.execute(f"drop table if exists {table} cascade")

    assert events == [
        psycopg.Begin(
            lsn=mock.ANY, xid=mock.ANY, final_lsn=mock.ANY, commit_time=mock.ANY
        ),
        psycopg.Relation(
            lsn=0,
            oid=mock.ANY,
            schema="public",
            name=table,
            replica_identity="d",
            columns=[
                psycopg.ColumnDef(name="id", flags={"key"}, type_oid=23, atttypmod=-1),
                psycopg.ColumnDef(name="name", flags=set(), type_oid=25, atttypmod=-1),
                psycopg.ColumnDef(name="qty", flags=set(), type_oid=23, atttypmod=-1),
            ],
        ),
        psycopg.Insert(
            lsn=mock.ANY,
            relation=psycopg.RelationRef(oid=mock.ANY, schema="public", name=table),
            new={"id": 1, "name": "one", "qty": 1},
        ),
        psycopg.Update(
            lsn=mock.ANY,
            relation=psycopg.RelationRef(oid=mock.ANY, schema="public", name=table),
            old=None,
            new={"id": 1, "name": "two", "qty": 2},
        ),
        psycopg.Message(
            lsn=mock.ANY,
            flags={"transactional"},
            message_lsn=mock.ANY,
            prefix="some-prefix",
            content=b"updated!",
        ),
        psycopg.Delete(
            lsn=mock.ANY,
            relation=psycopg.RelationRef(oid=mock.ANY, schema="public", name=table),
            old={"id": 1},
        ),
        psycopg.Commit(
            lsn=mock.ANY, commit_lsn=mock.ANY, end_lsn=mock.ANY, commit_time=mock.ANY
        ),
    ]
